services:
  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: Anhphuoc1@
      MYSQL_DATABASE: auth-service
    ports:
      - '3307:3306'
    volumes:
      - mysql-auth-data:/var/lib/mysql
    networks:
      - ecommerce-net
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - '3005:3005'
    env_file:
      - ./auth-service/.env
    environment:
      MYSQL_HOST: mysql-auth
      MYSQL_USER: root
      MYSQL_PASSWORD: Anhphuoc1@
      MYSQL_DATABASE: auth-service

    depends_on:
      mysql-auth:
        condition: service_healthy
    networks:
      - ecommerce-net

  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: Anhphuoc1@
      MYSQL_DATABASE: user-service
    ports:
      - '3308:3306'
    volumes:
      - mysql-user-data:/var/lib/mysql
    networks:
      - ecommerce-net
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - '8000:8000'
    env_file:
      - ./user-service/.env
    environment:
      MYSQL_HOST: mysql-user
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: Anhphuoc1@
      MYSQL_DATABASE: user-service
    depends_on:
      mysql-user:
        condition: service_healthy
    networks:
      - ecommerce-net

  mysql-product:
    image: mysql:8.0
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: Anhphuoc1@
      MYSQL_DATABASE: product-service
    ports:
      - '3309:3306'
    volumes:
      - mysql-product-data:/var/lib/mysql
    networks:
      - ecommerce-net
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - '8001:8001'
    env_file:
      - ./product-service/.env
    environment:
      MYSQL_HOST: mysql-product
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: Anhphuoc1@
      MYSQL_DATABASE: product-service
    depends_on:
      mysql-product:
        condition: service_healthy
    networks:
      - ecommerce-net

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - '5001:5001'
    env_file:
      - ./gateway-service/.env
    depends_on:
      - user-service
      - auth-service
      - product-service
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  mysql-auth-data:
  mysql-user-data:
  mysql-product-data:
